# Generated by Django 4.2.4 on 2023-08-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_remove_boardpost_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_credits',
            field=models.IntegerField(default=0),
        ),
    ]
