# Generated by Django 4.2.4 on 2023-08-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_user_total_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('undergraduate', '학부생'), ('master', '석사'), ('doctorate', '박사'), ('assistant_professor', '조교수'), ('associate_professor', '부교수'), ('professor', '정교수')], default='undergraduate', max_length=20),
        ),
    ]
