# Generated by Django 4.2.2 on 2023-08-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('Freshman', '새내기'), ('Undergraduate', '학부생'), ('Bachelor', '학사'), ('Master', '석사'), ('Doctorate', '박사'), ('Professor', '교수')], default='undergraduate', max_length=20),
        ),
    ]
