# Generated by Django 4.2.2 on 2023-08-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='social_posts/thumbnails/'),
        ),
    ]
